/**
 * Common lab tests with typical ADULT reference ranges.
 *
 * Ranges differ between labs, methods and populations. The parser always prefers the
 * range printed on the report itself and only falls back to these when none is printed.
 * Educational use only — not a diagnostic tool.
 */

export type Sex = 'male' | 'female';

export interface Range {
  low?: number;
  high?: number;
}

export interface TestDef {
  key: string;
  name: string;
  category: string;
  unit: string;
  aliases: string[];
  range: Range | { male: Range; female: Range };
  about: string; // what the test measures, in plain words
  low?: string; // what a low value can commonly be associated with
  high?: string; // what a high value can commonly be associated with
  /** Converts values reported in other common units into `unit`. */
  normalize?: (value: number) => number;
}

// Counts are sometimes reported per µL (7500) or in lakhs (2.5) instead of ×10³/µL.
const per1000 = (v: number) => (v > 1000 ? v / 1000 : v);
const plateletScale = (v: number) => (v > 1000 ? v / 1000 : v < 10 ? v * 100 : v);

export const TESTS: TestDef[] = [
  // ---------------- Complete blood count ----------------
  {
    key: 'hemoglobin',
    name: 'Hemoglobin',
    category: 'Blood count',
    unit: 'g/dL',
    aliases: ['haemoglobin', 'hemoglobin', 'hb', 'hgb'],
    range: { male: { low: 13, high: 17 }, female: { low: 12, high: 15 } },
    about: 'The protein in red blood cells that carries oxygen around the body.',
    low: 'Low levels are often linked to anaemia, for example from low iron, B12 or folate, or blood loss.',
    high: 'High levels can be seen with dehydration, smoking, or living at high altitude.',
  },
  {
    key: 'rbc',
    name: 'RBC count',
    category: 'Blood count',
    unit: 'million/µL',
    aliases: ['rbc count', 'red blood cell count', 'total rbc', 'rbc', 'erythrocyte count'],
    range: { male: { low: 4.5, high: 5.5 }, female: { low: 3.8, high: 4.8 } },
    about: 'How many red blood cells you have.',
    low: 'Often seen alongside anaemia.',
    high: 'Can be seen with dehydration or conditions that increase red cell production.',
  },
  {
    key: 'pcv',
    name: 'Hematocrit (PCV)',
    category: 'Blood count',
    unit: '%',
    aliases: ['packed cell volume', 'hematocrit', 'haematocrit', 'pcv', 'hct'],
    range: { male: { low: 40, high: 50 }, female: { low: 36, high: 46 } },
    about: 'The share of your blood volume made up of red blood cells.',
    low: 'Usually moves with hemoglobin; low values often accompany anaemia.',
    high: 'Can rise with dehydration.',
  },
  {
    key: 'mcv',
    name: 'MCV',
    category: 'Blood count',
    unit: 'fL',
    aliases: ['mean corpuscular volume', 'mcv'],
    range: { low: 83, high: 101 },
    about: 'The average size of your red blood cells.',
    low: 'Small red cells are commonly linked to iron deficiency or thalassemia trait.',
    high: 'Large red cells are commonly linked to low B12 or folate, alcohol or thyroid issues.',
  },
  {
    key: 'mch',
    name: 'MCH',
    category: 'Blood count',
    unit: 'pg',
    aliases: ['mean corpuscular hemoglobin', 'mean corpuscular haemoglobin', 'mch'],
    range: { low: 27, high: 32 },
    about: 'The average amount of hemoglobin in each red blood cell.',
  },
  {
    key: 'mchc',
    name: 'MCHC',
    category: 'Blood count',
    unit: 'g/dL',
    aliases: ['mean corpuscular hemoglobin concentration', 'mean corpuscular haemoglobin concentration', 'mchc'],
    range: { low: 31.5, high: 34.5 },
    about: 'How concentrated the hemoglobin is inside red blood cells.',
  },
  {
    key: 'rdw',
    name: 'RDW',
    category: 'Blood count',
    unit: '%',
    aliases: ['red cell distribution width', 'rdw-cv', 'rdw cv', 'rdw'],
    range: { low: 11.6, high: 14 },
    about: 'How much your red blood cells vary in size.',
    high: 'A wide spread can be an early sign of nutritional deficiencies.',
  },
  {
    key: 'wbc',
    name: 'Total WBC count',
    category: 'Blood count',
    unit: '×10³/µL',
    aliases: ['total leucocyte count', 'total leukocyte count', 'total wbc count', 'white blood cell count', 'wbc count', 'tlc', 'wbc'],
    range: { low: 4, high: 11 },
    about: 'White blood cells fight infection.',
    low: 'Low counts can follow viral infections or some medicines.',
    high: 'High counts are commonly seen with infection, inflammation or stress.',
    normalize: per1000,
  },
  {
    key: 'neutrophils',
    name: 'Neutrophils',
    category: 'Blood count',
    unit: '%',
    aliases: ['neutrophils', 'neutrophil', 'polymorphs'],
    range: { low: 40, high: 80 },
    about: 'The most common white cell; first responders to bacterial infection.',
  },
  {
    key: 'lymphocytes',
    name: 'Lymphocytes',
    category: 'Blood count',
    unit: '%',
    aliases: ['lymphocytes', 'lymphocyte'],
    range: { low: 20, high: 40 },
    about: 'White cells central to fighting viruses and making antibodies.',
  },
  {
    key: 'eosinophils',
    name: 'Eosinophils',
    category: 'Blood count',
    unit: '%',
    aliases: ['eosinophils', 'eosinophil'],
    range: { low: 1, high: 6 },
    about: 'White cells involved in allergies and parasitic infections.',
    high: 'Often raised with allergies, asthma or parasites.',
  },
  {
    key: 'monocytes',
    name: 'Monocytes',
    category: 'Blood count',
    unit: '%',
    aliases: ['monocytes', 'monocyte'],
    range: { low: 2, high: 10 },
    about: 'White cells that clean up debris and fight infection.',
  },
  {
    key: 'basophils',
    name: 'Basophils',
    category: 'Blood count',
    unit: '%',
    aliases: ['basophils', 'basophil'],
    range: { low: 0, high: 2 },
    about: 'A rare white cell type involved in allergic reactions.',
  },
  {
    key: 'platelets',
    name: 'Platelet count',
    category: 'Blood count',
    unit: '×10³/µL',
    aliases: ['platelet count', 'platelets', 'plt'],
    range: { low: 150, high: 410 },
    about: 'Platelets help your blood clot.',
    low: 'Low platelets can be seen with viral fevers such as dengue, and some medicines.',
    high: 'High platelets can follow inflammation, infection or iron deficiency.',
    normalize: plateletScale,
  },
  {
    key: 'esr',
    name: 'ESR',
    category: 'Inflammation',
    unit: 'mm/hr',
    aliases: ['erythrocyte sedimentation rate', 'esr'],
    range: { male: { low: 0, high: 15 }, female: { low: 0, high: 20 } },
    about: 'A general, non-specific marker of inflammation in the body.',
    high: 'Raised with infection, inflammation and also with age and pregnancy.',
  },
  {
    key: 'crp',
    name: 'CRP',
    category: 'Inflammation',
    unit: 'mg/L',
    aliases: ['c-reactive protein', 'c reactive protein', 'crp'],
    range: { low: 0, high: 5 },
    about: 'A protein the liver makes during inflammation.',
    high: 'Raised with infection or inflammation.',
  },

  // ---------------- Sugar ----------------
  {
    key: 'fbs',
    name: 'Fasting glucose',
    category: 'Blood sugar',
    unit: 'mg/dL',
    aliases: ['fasting blood sugar', 'fasting plasma glucose', 'glucose fasting', 'glucose (fasting)', 'fasting glucose', 'fbs', 'fpg'],
    range: { low: 70, high: 100 },
    about: 'Blood sugar after not eating for 8+ hours.',
    low: 'Low fasting sugar can cause shakiness or dizziness.',
    high: 'Values of 100–125 are commonly labelled prediabetes range, and 126+ (confirmed on repeat) the diabetes range.',
  },
  {
    key: 'ppbs',
    name: 'Post-meal glucose',
    category: 'Blood sugar',
    unit: 'mg/dL',
    aliases: ['post prandial blood sugar', 'postprandial blood sugar', 'post prandial glucose', 'postprandial glucose', 'glucose pp', 'ppbs', 'pp blood sugar', 'plasma glucose pp'],
    range: { low: 70, high: 140 },
    about: 'Blood sugar about 2 hours after a meal.',
    high: 'Values of 140–199 are commonly labelled prediabetes range, and 200+ the diabetes range.',
  },
  {
    key: 'rbs',
    name: 'Random glucose',
    category: 'Blood sugar',
    unit: 'mg/dL',
    aliases: ['random blood sugar', 'random plasma glucose', 'glucose random', 'rbs'],
    range: { low: 70, high: 140 },
    about: 'Blood sugar at any time of day.',
  },
  {
    key: 'hba1c',
    name: 'HbA1c',
    category: 'Blood sugar',
    unit: '%',
    aliases: ['glycated hemoglobin', 'glycosylated hemoglobin', 'glycated haemoglobin', 'hba1c', 'hb a1c', 'a1c'],
    range: { low: 4, high: 5.6 },
    about: 'Your average blood sugar over the past 2–3 months.',
    high: '5.7–6.4% is commonly labelled the prediabetes range, and 6.5%+ the diabetes range.',
  },

  {
    key: 'eag',
    name: 'Estimated average glucose',
    category: 'Blood sugar',
    unit: 'mg/dL',
    aliases: ['estimated average glucose', 'average blood glucose', 'mean blood glucose', 'eag'],
    range: { low: 70, high: 117 },
    about: 'Your HbA1c converted into an average blood sugar number.',
  },
  // ---------------- Lipids ----------------
  {
    key: 'cholesterol',
    name: 'Total cholesterol',
    category: 'Lipids',
    unit: 'mg/dL',
    aliases: ['total cholesterol', 'cholesterol total', 'serum cholesterol', 'cholesterol'],
    range: { high: 200 },
    about: 'All the cholesterol in your blood, good and bad.',
    high: 'Higher levels are associated with greater heart disease risk over time.',
  },
  {
    key: 'ldl',
    name: 'LDL cholesterol',
    category: 'Lipids',
    unit: 'mg/dL',
    aliases: ['cholesterol ldl', 'ldl cholesterol', 'ldl-cholesterol', 'ldl-c', 'ldl direct', 'ldl'],
    range: { high: 100 },
    about: 'Often called "bad" cholesterol; it can build up in artery walls.',
    high: 'Higher LDL is a major, modifiable heart-disease risk factor.',
  },
  {
    key: 'hdl',
    name: 'HDL cholesterol',
    category: 'Lipids',
    unit: 'mg/dL',
    aliases: ['cholesterol hdl', 'hdl cholesterol', 'hdl-cholesterol', 'hdl-c', 'hdl direct', 'hdl'],
    range: { male: { low: 40 }, female: { low: 50 } },
    about: '"Good" cholesterol that helps remove other cholesterol from the blood.',
    low: 'Low HDL is associated with higher heart-disease risk; exercise can raise it.',
  },
  {
    key: 'triglycerides',
    name: 'Triglycerides',
    category: 'Lipids',
    unit: 'mg/dL',
    aliases: ['triglycerides', 'triglyceride', 'tg', 'serum triglycerides'],
    range: { high: 150 },
    about: 'A type of fat in the blood that rises with sugar, refined carbs and alcohol.',
    high: 'Raised levels are linked to heart risk and, when very high, pancreatitis.',
  },
  {
    key: 'vldl',
    name: 'VLDL cholesterol',
    category: 'Lipids',
    unit: 'mg/dL',
    aliases: ['cholesterol vldl', 'vldl cholesterol', 'vldl-cholesterol', 'vldl'],
    range: { low: 5, high: 40 },
    about: 'A cholesterol carrier that also transports triglycerides.',
  },

  {
    key: 'non_hdl',
    name: 'Non-HDL cholesterol',
    category: 'Lipids',
    unit: 'mg/dL',
    aliases: ['non hdl cholesterol', 'non-hdl cholesterol', 'non hdl c', 'non-hdl'],
    range: { high: 130 },
    about: 'All the "bad" cholesterol types together (total minus HDL).',
    high: 'A higher value is associated with greater heart-disease risk.',
  },
  {
    key: 'chol_hdl_ratio',
    name: 'Cholesterol / HDL ratio',
    category: 'Lipids',
    unit: 'ratio',
    aliases: ['total cholesterol hdl ratio', 'cholesterol hdl ratio', 'chol hdl ratio', 'tc hdl ratio', 'tc/hdl'],
    range: { high: 5 },
    about: 'Total cholesterol divided by HDL. Lower is better.',
  },
  {
    key: 'ldl_hdl_ratio',
    name: 'LDL / HDL ratio',
    category: 'Lipids',
    unit: 'ratio',
    aliases: ['ldl hdl ratio', 'ldl/hdl'],
    range: { high: 3.5 },
    about: 'LDL divided by HDL. Lower is better.',
  },
  // ---------------- Kidney ----------------
  {
    key: 'creatinine',
    name: 'Creatinine',
    category: 'Kidney',
    unit: 'mg/dL',
    aliases: ['serum creatinine', 'creatinine'],
    range: { male: { low: 0.7, high: 1.3 }, female: { low: 0.6, high: 1.1 } },
    about: 'A waste product from muscles that healthy kidneys filter out.',
    high: 'Higher values can mean the kidneys are filtering less well, or dehydration or high muscle mass.',
  },
  {
    key: 'urea',
    name: 'Blood urea',
    category: 'Kidney',
    unit: 'mg/dL',
    aliases: ['blood urea', 'serum urea', 'urea'],
    range: { low: 15, high: 40 },
    about: 'A waste product from protein breakdown, cleared by the kidneys.',
    high: 'Can rise with dehydration, high protein intake or reduced kidney function.',
  },
  {
    key: 'bun',
    name: 'BUN',
    category: 'Kidney',
    unit: 'mg/dL',
    aliases: ['blood urea nitrogen', 'bun'],
    range: { low: 7, high: 20 },
    about: 'The nitrogen part of urea in your blood.',
  },
  {
    key: 'uric_acid',
    name: 'Uric acid',
    category: 'Kidney',
    unit: 'mg/dL',
    aliases: ['serum uric acid', 'uric acid'],
    range: { male: { low: 3.5, high: 7.2 }, female: { low: 2.6, high: 6 } },
    about: 'A waste product from breaking down purines (found in some foods).',
    high: 'High levels can lead to gout or kidney stones.',
  },
  {
    key: 'egfr',
    name: 'eGFR',
    category: 'Kidney',
    unit: 'mL/min/1.73m²',
    aliases: ['estimated glomerular filtration rate', 'egfr', 'e gfr', 'gfr'],
    range: { low: 90 },
    about: 'An estimate of how well your kidneys filter blood, calculated from creatinine, age and sex.',
    low: 'Lower values can mean reduced kidney function; 60–89 is often mildly reduced, below 60 worth closer review.',
  },
  {
    key: 'phosphorus',
    name: 'Phosphorus',
    category: 'Electrolytes',
    unit: 'mg/dL',
    aliases: ['serum phosphorus', 'inorganic phosphorus', 'phosphorus', 'phosphate'],
    range: { low: 2.5, high: 4.5 },
    about: 'A mineral that works with calcium for bones and energy.',
  },
  {
    key: 'magnesium',
    name: 'Magnesium',
    category: 'Electrolytes',
    unit: 'mg/dL',
    aliases: ['serum magnesium', 'magnesium', 'mg++'],
    range: { low: 1.7, high: 2.2 },
    about: 'A mineral for muscles, nerves and heart rhythm.',
  },
  {
    key: 'sodium',
    name: 'Sodium',
    category: 'Electrolytes',
    unit: 'mmol/L',
    aliases: ['serum sodium', 'sodium', 'na+', 'na'],
    range: { low: 136, high: 145 },
    about: 'An electrolyte that controls fluid balance and nerve signals.',
  },
  {
    key: 'potassium',
    name: 'Potassium',
    category: 'Electrolytes',
    unit: 'mmol/L',
    aliases: ['serum potassium', 'potassium', 'k+'],
    range: { low: 3.5, high: 5.1 },
    about: 'An electrolyte essential for heart rhythm and muscles.',
  },
  {
    key: 'chloride',
    name: 'Chloride',
    category: 'Electrolytes',
    unit: 'mmol/L',
    aliases: ['serum chloride', 'chloride', 'cl-'],
    range: { low: 98, high: 107 },
    about: 'An electrolyte that works with sodium to balance fluids.',
  },
  {
    key: 'calcium',
    name: 'Calcium',
    category: 'Electrolytes',
    unit: 'mg/dL',
    aliases: ['serum calcium', 'total calcium', 'calcium'],
    range: { low: 8.6, high: 10.3 },
    about: 'A mineral for bones, muscles and nerves.',
  },

  // ---------------- Liver ----------------
  {
    key: 'bilirubin_total',
    name: 'Total bilirubin',
    category: 'Liver',
    unit: 'mg/dL',
    aliases: ['bilirubin total', 'total bilirubin', 'serum bilirubin', 'bilirubin'],
    range: { low: 0.3, high: 1.2 },
    about: 'A yellow pigment from the normal breakdown of red blood cells, cleared by the liver.',
    high: 'High levels can cause yellowing of the eyes or skin; often harmless (e.g. Gilbert syndrome) but worth reviewing.',
  },
  {
    key: 'bilirubin_direct',
    name: 'Direct bilirubin',
    category: 'Liver',
    unit: 'mg/dL',
    aliases: ['bilirubin direct', 'direct bilirubin', 'conjugated bilirubin', 'bilirubin (direct)'],
    range: { low: 0, high: 0.3 },
    about: 'Bilirubin the liver has already processed.',
  },
  {
    key: 'bilirubin_indirect',
    name: 'Indirect bilirubin',
    category: 'Liver',
    unit: 'mg/dL',
    aliases: ['bilirubin indirect', 'indirect bilirubin', 'unconjugated bilirubin', 'bilirubin (indirect)'],
    range: { low: 0.2, high: 0.8 },
    about: 'Bilirubin before the liver has processed it.',
  },
  {
    key: 'alt',
    name: 'ALT (SGPT)',
    category: 'Liver',
    unit: 'U/L',
    aliases: ['alanine aminotransferase', 'alanine transaminase', 'sgpt', 'alt'],
    range: { low: 0, high: 45 },
    about: 'A liver enzyme. It leaks into the blood when liver cells are irritated.',
    high: 'Commonly raised with fatty liver, alcohol, some medicines or hepatitis.',
  },
  {
    key: 'ast',
    name: 'AST (SGOT)',
    category: 'Liver',
    unit: 'U/L',
    aliases: ['aspartate aminotransferase', 'aspartate transaminase', 'sgot', 'ast'],
    range: { low: 0, high: 40 },
    about: 'An enzyme found in the liver, heart and muscles.',
    high: 'Can rise with liver irritation and also after hard exercise.',
  },
  {
    key: 'alp',
    name: 'Alkaline phosphatase',
    category: 'Liver',
    unit: 'U/L',
    aliases: ['alkaline phosphatase', 'alp'],
    range: { low: 44, high: 147 },
    about: 'An enzyme from the liver and bones.',
  },
  {
    key: 'ggt',
    name: 'GGT',
    category: 'Liver',
    unit: 'U/L',
    aliases: ['gamma glutamyl transferase', 'gamma-glutamyl transferase', 'ggt', 'ggtp'],
    range: { low: 0, high: 55 },
    about: 'A liver enzyme sensitive to alcohol and bile flow.',
  },
  {
    key: 'total_protein',
    name: 'Total protein',
    category: 'Liver',
    unit: 'g/dL',
    aliases: ['total protein', 'serum protein', 'total proteins'],
    range: { low: 6, high: 8.3 },
    about: 'All the protein in your blood (albumin plus globulins).',
  },
  {
    key: 'albumin',
    name: 'Albumin',
    category: 'Liver',
    unit: 'g/dL',
    aliases: ['serum albumin', 'albumin'],
    range: { low: 3.5, high: 5 },
    about: 'The main blood protein, made by the liver.',
  },

  {
    key: 'globulin',
    name: 'Globulin',
    category: 'Liver',
    unit: 'g/dL',
    aliases: ['serum globulin', 'globulin'],
    range: { low: 2, high: 3.5 },
    about: 'A group of blood proteins that includes antibodies.',
  },
  {
    key: 'ag_ratio',
    name: 'A/G ratio',
    category: 'Liver',
    unit: 'ratio',
    aliases: ['albumin globulin ratio', 'a g ratio', 'a/g ratio', 'a:g ratio'],
    range: { low: 1, high: 2.1 },
    about: 'Albumin divided by globulin.',
  },
  // ---------------- Thyroid ----------------
  {
    key: 'tsh',
    name: 'TSH',
    category: 'Thyroid',
    unit: 'µIU/mL',
    aliases: ['thyroid stimulating hormone', 'tsh', 'ultrasensitive tsh', 'tsh ultrasensitive'],
    range: { low: 0.4, high: 4.5 },
    about: 'The brain\'s signal to the thyroid gland. It moves opposite to thyroid activity.',
    low: 'A low TSH can point to an overactive thyroid.',
    high: 'A high TSH can point to an underactive thyroid.',
  },
  {
    key: 't3',
    name: 'Total T3',
    category: 'Thyroid',
    unit: 'ng/dL',
    aliases: ['total t3', 'triiodothyronine', 't3 total', 't3'],
    range: { low: 80, high: 200 },
    about: 'An active thyroid hormone.',
  },
  {
    key: 'ft3',
    name: 'Free T3',
    category: 'Thyroid',
    unit: 'pg/mL',
    aliases: ['free t3', 'free triiodothyronine', 'ft3'],
    range: { low: 2, high: 4.4 },
    about: 'The unbound, active form of T3.',
  },
  {
    key: 't4',
    name: 'Total T4',
    category: 'Thyroid',
    unit: 'µg/dL',
    aliases: ['total t4', 'thyroxine', 't4 total', 't4'],
    range: { low: 5, high: 12 },
    about: 'The main hormone the thyroid releases.',
  },
  {
    key: 'ft4',
    name: 'Free T4',
    category: 'Thyroid',
    unit: 'ng/dL',
    aliases: ['free t4', 'free thyroxine', 'ft4'],
    range: { low: 0.8, high: 1.8 },
    about: 'The unbound, active form of T4.',
  },

  // ---------------- Vitamins & iron ----------------
  {
    key: 'vitamin_d',
    name: 'Vitamin D (25-OH)',
    category: 'Vitamins & iron',
    unit: 'ng/mL',
    aliases: ['25-hydroxy vitamin d', '25 hydroxy vitamin d', '25-oh vitamin d', 'vitamin d3', 'vitamin d total', 'vitamin d'],
    range: { low: 30, high: 100 },
    about: 'Vitamin D supports bones, muscles and immunity.',
    low: 'Low vitamin D is very common, especially with little sun exposure.',
  },
  {
    key: 'b12',
    name: 'Vitamin B12',
    category: 'Vitamins & iron',
    unit: 'pg/mL',
    aliases: ['vitamin b12', 'vitamin b 12', 'cyanocobalamin', 'cobalamin', 'b12'],
    range: { low: 200, high: 900 },
    about: 'Needed for nerves and making red blood cells.',
    low: 'Low B12 is common in vegetarians and can cause tiredness, tingling or anaemia.',
  },
  {
    key: 'iron',
    name: 'Serum iron',
    category: 'Vitamins & iron',
    unit: 'µg/dL',
    aliases: ['serum iron', 'iron'],
    range: { low: 60, high: 170 },
    about: 'The amount of iron circulating in your blood.',
  },
  {
    key: 'tibc',
    name: 'TIBC',
    category: 'Vitamins & iron',
    unit: 'µg/dL',
    aliases: ['total iron binding capacity', 'tibc'],
    range: { low: 250, high: 450 },
    about: 'How much iron your blood could carry. It rises when iron stores are low.',
  },
  {
    key: 'ferritin',
    name: 'Ferritin',
    category: 'Vitamins & iron',
    unit: 'ng/mL',
    aliases: ['serum ferritin', 'ferritin'],
    range: { male: { low: 30, high: 400 }, female: { low: 15, high: 150 } },
    about: 'Your body\'s iron stores.',
    low: 'Low ferritin is the most specific sign of iron deficiency.',
  },
];
